version: 2
updates:
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /ocr
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /clamav
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: pip
    directory: /ocr
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
