-- Unsubscribe links now travel as URL fragments and are exchanged for a browser grant keyed on the
-- SHA-256 digest of the raw token. The digest is generated by the database so dispatch keeps
-- rendering links off the stored raw token while lookups never touch it. Expand-only: older
-- binaries neither read nor write this column.
ALTER TABLE campaign_delivery
    ADD COLUMN unsubscribe_token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin
        GENERATED ALWAYS AS (LOWER(SHA2(unsubscribe_token, 256))) STORED
        COMMENT 'SHA-256 digest of unsubscribe_token; exchange lookup key'
        AFTER unsubscribe_token,
    ADD UNIQUE KEY uq_campaign_delivery_token_hash (unsubscribe_token_hash);
