CREATE TABLE appi_incident (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id INT NOT NULL,
    title VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'triage',
    severity VARCHAR(32) NOT NULL DEFAULT 'undetermined',
    reportable BOOLEAN NOT NULL DEFAULT FALSE,
    occurred_from DATETIME NULL,
    occurred_to DATETIME NULL,
    detected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_notified_at DATETIME NULL,
    ppc_reported_at DATETIME NULL,
    individuals_notified_at DATETIME NULL,
    summary TEXT NULL,
    containment TEXT NULL,
    created_by INT NULL,
    updated_by INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_appi_incident_org FOREIGN KEY (org_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_appi_incident_created_by FOREIGN KEY (created_by) REFERENCES app_user(id) ON DELETE SET NULL,
    CONSTRAINT fk_appi_incident_updated_by FOREIGN KEY (updated_by) REFERENCES app_user(id) ON DELETE SET NULL,
    INDEX idx_appi_incident_org_status (org_id, status, detected_at),
    INDEX idx_appi_incident_org_detected (org_id, detected_at)
) DEFAULT CHARSET=utf8mb4;
