package ooo.klae.connex.backend.services;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ooo.klae.connex.backend.mappers.CompanyMapper;
import ooo.klae.connex.backend.mappers.DealMapper;
import ooo.klae.connex.backend.mappers.PersonMapper;
import ooo.klae.connex.backend.mappers.TagMapper;
import ooo.klae.connex.backend.beans.Company;
import ooo.klae.connex.backend.beans.Deal;
import ooo.klae.connex.backend.beans.Person;
import ooo.klae.connex.backend.beans.Tag;
import ooo.klae.connex.backend.exceptions.ResourceNotFoundException;

import java.util.List;
import java.util.Set;

import lombok.RequiredArgsConstructor;

/**
 * Business logic for {@code Company} operations.
 * Handles mapping between {@code CompanyDto} and {@code Company} bean.
 * Delegates persistence to {@code CompanyMapper}.
 */

@Service
@RequiredArgsConstructor
public class CompanyService {
    private final CompanyMapper companyMapper;
    private final TagMapper tagMapper;
    private final PersonMapper personMapper;
    private final DealMapper dealMapper;
    private final AuditService auditService;

    private static final Set<String> AUDIT_FIELDS =
        Set.of("name", "website", "industry", "phone", "address", "logoUrl");

    /**
     * Retrieves all {@code Company} records.
     *
     * @return
     */
    public List<Company> getAllCompanies() {
        return companyMapper.getAllCompanies();
    }

    public List<Company> getCompaniesByTagId(int tagId) {
        return companyMapper.getCompaniesByTagId(tagId);
    }

    /**
     * Retrieves a {@code Company} by ID, throwing a
     * {@code ResourceNotFoundException} if not found.
     *
     * @param id
     * @return
     */
    public Company getCompanyById(int id) {
        Company company = companyMapper.getCompanyById(id);
        if (company == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        return company;
    }

    /**
     * Creates a new {@code Company}. The ID is auto-generated by the database.
     *
     * @param company
     * @return
     */
    public Company createCompany(Company company) {
        companyMapper.insert(company);
        auditService.record("company.create", "company", company.getId(), company.getName(),
            "Created company " + company.getName(),
            auditService.diff(null, company, AUDIT_FIELDS));
        return company;
    }

    /**
     * Updates an existing {@code Company} record.
     *
     * @param id
     * @param company
     * @return
     */
    public Company updateCompany(int id, Company company) {
        Company before = companyMapper.getCompanyById(id);
        if (before == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        company.setId(id);
        companyMapper.update(company);
        auditService.record("company.update", "company", id, company.getName(),
            "Updated company " + company.getName(),
            auditService.diff(before, company, AUDIT_FIELDS));
        return company;
    }

    /**
     * Deletes a {@code Company} record by ID, throwing a
     * {@code ResourceNotFoundException} if not found.
     *
     * @param id
     */
    public void deleteCompany(int id) {
        Company before = companyMapper.getCompanyById(id);
        if (before == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        companyMapper.delete(id);
        auditService.record("company.delete", "company", id, before.getName(),
            "Deleted company " + before.getName(),
            auditService.diff(before, null, AUDIT_FIELDS));
    }

    /**
     * Retrieves the tags associated with a company.
     * @param companyId
     * @return
     */
    public List<Tag> getTagsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return tagMapper.getTagsByCompanyId(companyId);
    }

    /**
     * Adds a tag to a company.
     * @param companyId
     * @param tagId
     */
    public void addTag(int companyId, int tagId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        if (tagMapper.getTagById(tagId) == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        companyMapper.addTag(companyId, tagId);
        auditService.record("company.addTag", "company", companyId, null, "Tag added to company", null);
    }

    /**
     * Removes a tag from a company.
     * @param companyId
     * @param tagId
     */
    public void removeTag(int companyId, int tagId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        companyMapper.removeTag(companyId, tagId);
        auditService.record("company.removeTag", "company", companyId, null, "Tag removed from company", null);
    }

    /**
     * Replaces the tags associated with a company.
     * @param companyId
     * @param tagIds
     * @return
     */
    @Transactional
    public List<Tag> replaceTags(int companyId, List<Integer> tagIds) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        companyMapper.clearTags(companyId);
        if (tagIds != null && !tagIds.isEmpty()) companyMapper.insertTags(companyId, tagIds);
        auditService.record("company.replaceTags", "company", companyId, null, "Tags replaced for company", null);
        return tagMapper.getTagsByCompanyId(companyId);
    }

    /**
     * Retrieves the people associated with a company.
     * @param companyId
     * @return
     */
    public List<Person> getPersonsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return personMapper.getPersonsByCompanyId(companyId);
    }

    /**
     * Retrieves the deals associated with a company.
     * @param companyId
     * @return
     */
    public List<Deal> getDealsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return dealMapper.getDealsByCompanyId(companyId);
    }
}
