package ooo.klae.connex.backend.services;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ooo.klae.connex.backend.mappers.CompanyMapper;
import ooo.klae.connex.backend.mappers.TagMapper;
import ooo.klae.connex.backend.beans.Company;
import ooo.klae.connex.backend.beans.Tag;
import ooo.klae.connex.backend.exceptions.ResourceNotFoundException;

import java.util.List;

import lombok.RequiredArgsConstructor;

/**
 * Business logic for {@code Company} operations.
 * Handles mapping between {@code CompanyDto} and {@code Company} bean.
 * Delegates persistence to {@code CompanyMapper}.
 */

@Service
@RequiredArgsConstructor
public class CompanyService {
    private final CompanyMapper companyMapper;
    private final TagMapper tagMapper;

    /**
     * Retrieves all {@code Company} records.
     *
     * @return
     */
    public List<Company> getAllCompanies() {
        return companyMapper.getAllCompanies();
    }

    public List<Company> getCompaniesByTagId(int tagId) {
        return companyMapper.getCompaniesByTagId(tagId);
    }

    /**
     * Retrieves a {@code Company} by ID, throwing a
     * {@code ResourceNotFoundException} if not found.
     *
     * @param id
     * @return
     */
    public Company getCompanyById(int id) {
        Company company = companyMapper.getCompanyById(id);
        if (company == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        return company;
    }

    /**
     * Creates a new {@code Company}. The ID is auto-generated by the database.
     *
     * @param company
     * @return
     */
    public Company createCompany(Company company) {
        companyMapper.insert(company);
        return company;
    }

    /**
     * Updates an existing {@code Company} record.
     *
     * @param id
     * @param company
     * @return
     */
    public Company updateCompany(int id, Company company) {
        if (companyMapper.getCompanyById(id) == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        company.setId(id);
        companyMapper.update(company);
        return company;
    }

    /**
     * Deletes a {@code Company} record by ID, throwing a
     * {@code ResourceNotFoundException} if not found.
     *
     * @param id
     */
    public void deleteCompany(int id) {
        if (companyMapper.getCompanyById(id) == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        companyMapper.delete(id);
    }

    public List<Tag> getTagsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return tagMapper.getTagsByCompanyId(companyId);
    }

    public void addTag(int companyId, int tagId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        if (tagMapper.getTagById(tagId) == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        companyMapper.addTag(companyId, tagId);
    }

    public void removeTag(int companyId, int tagId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        companyMapper.removeTag(companyId, tagId);
    }

    @Transactional
    public List<Tag> replaceTags(int companyId, List<Integer> tagIds) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        companyMapper.clearTags(companyId);
        if (tagIds != null && !tagIds.isEmpty()) companyMapper.insertTags(companyId, tagIds);
        return tagMapper.getTagsByCompanyId(companyId);
    }
}
