package ooo.klae.connex.backend.services;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ooo.klae.connex.backend.mappers.CompanyMapper;
import ooo.klae.connex.backend.mappers.DealMapper;
import ooo.klae.connex.backend.mappers.PersonMapper;
import ooo.klae.connex.backend.mappers.TagMapper;
import ooo.klae.connex.backend.beans.Company;
import ooo.klae.connex.backend.beans.Deal;
import ooo.klae.connex.backend.beans.Person;
import ooo.klae.connex.backend.beans.Tag;
import ooo.klae.connex.backend.exceptions.ResourceNotFoundException;
import ooo.klae.connex.backend.exceptions.DuplicateResourceException;

import java.util.List;
import java.util.Set;

import lombok.RequiredArgsConstructor;

/**
 * Business logic for {@code Company} operations.
 * Handles mapping between {@code CompanyDto} and {@code Company} bean.
 * Delegates persistence to {@code CompanyMapper}.
 */

@Service
@RequiredArgsConstructor
public class CompanyService {
    private final CompanyMapper companyMapper;
    private final TagMapper tagMapper;
    private final PersonMapper personMapper;
    private final DealMapper dealMapper;
    private final AuditService auditService;
    private final WorkspaceService workspaceService;

    private static final Set<String> AUDIT_FIELDS =
        Set.of("name", "website", "industry", "phone", "address", "logoUrl");

    /**
     * Retrieves all {@code Company} records.
     *
     * @return
     */
    public List<Company> getAllCompanies() {
        return companyMapper.getAllCompanies();
    }

    public List<Company> getCompaniesByTagId(int tagId) {
        return companyMapper.getCompaniesByTagId(tagId);
    }

    /**
     * Retrieves a {@code Company} by ID, throwing a
     * {@code ResourceNotFoundException} if not found.
     *
     * @param id
     * @return
     */
    public Company getCompanyById(int id) {
        Company company = companyMapper.getCompanyById(id);
        if (company == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        company.setDeals(dealMapper.getDealsByCompanyId(
            workspaceService.getCurrentWorkspaceId(),
            id
        ).toArray(Deal[]::new));
        return company;
    }

    /**
     * Creates a new {@code Company}. The ID is auto-generated by the database.
     *
     * @param company
     * @return
     */
    public Company createCompany(Company company) {
        assertUniqueWebsite(company);
        companyMapper.insert(company);
        auditService.record("company.create", "company", company.getId(), company.getName(),
            "Created company " + company.getName(),
            auditService.diff(null, company, AUDIT_FIELDS));
        return company;
    }

    /**
     * Ensures the website is unique.
     * @param company
     */
    private void assertUniqueWebsite(Company company) {
        String target = normalizeWebsite(company.getWebsite());
        if (target.isEmpty()) return;
        for (Company other : companyMapper.getCompaniesWithWebsite()) {
            if (other.getId() == company.getId()) continue; // skip self (id is 0 on create)
            if (target.equals(normalizeWebsite(other.getWebsite())))
                throw new DuplicateResourceException("website", "A company with this website already exists");
        }
    }

    /**
     * Normalizes a website for comparison.
     * Lowercases, trims, removes leading "www." and trailing slashes.
     * @param website
     * @return
     */
    private static String normalizeWebsite(String website) {
        if (website == null) return "";
        String w = website.trim().toLowerCase();
        w = w.replaceFirst("^https?://", "");
        w = w.replaceFirst("^www\\.", "");
        w = w.replaceAll("/+$", "");
        return w;
    }

    /**
     * Updates an existing {@code Company} record.
     *
     * @param id
     * @param company
     * @return
     */
    public Company updateCompany(int id, Company company) {
        Company before = companyMapper.getCompanyById(id);
        if (before == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        company.setId(id);
        assertUniqueWebsite(company);
        companyMapper.update(company);
        auditService.record("company.update", "company", id, company.getName(),
            "Updated company " + company.getName(),
            auditService.diff(before, company, AUDIT_FIELDS));
        return company;
    }

    /**
     * Deletes a {@code Company} record by ID, throwing a
     * {@code ResourceNotFoundException} if not found.
     *
     * @param id
     */
    public void deleteCompany(int id) {
        Company before = companyMapper.getCompanyById(id);
        if (before == null) throw new ResourceNotFoundException("Company not found with id: " + id);
        companyMapper.delete(id);
        auditService.record("company.delete", "company", id, before.getName(),
            "Deleted company " + before.getName(),
            auditService.diff(before, null, AUDIT_FIELDS));
    }

    /**
     * Retrieves the tags associated with a company.
     * @param companyId
     * @return
     */
    public List<Tag> getTagsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return tagMapper.getTagsByCompanyId(companyId);
    }

    /**
     * Adds a tag to a company.
     * @param companyId
     * @param tagId
     */
    public void addTag(int companyId, int tagId) {
        Company company = companyMapper.getCompanyById(companyId);
        if (company == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        Tag tag = tagMapper.getTagById(tagId);
        if (tag == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        companyMapper.addTag(companyId, tagId);
        auditService.record("company.addTag", "company", companyId, company.getName(),
            "Tagged " + company.getName() + " with " + tag.getName(),
            auditService.singleChange("tag", null, tag.getName()));
    }

    /**
     * Removes a tag from a company.
     * @param companyId
     * @param tagId
     */
    public void removeTag(int companyId, int tagId) {
        Company company = companyMapper.getCompanyById(companyId);
        if (company == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        Tag tag = tagMapper.getTagById(tagId);
        companyMapper.removeTag(companyId, tagId);
        String tagName = tag != null ? tag.getName() : "#" + tagId;
        auditService.record("company.removeTag", "company", companyId, company.getName(),
            "Removed tag " + tagName + " from " + company.getName(),
            auditService.singleChange("tag", tagName, null));
    }

    /**
     * Replaces the tags associated with a company.
     * @param companyId
     * @param tagIds
     * @return
     */
    @Transactional
    public List<Tag> replaceTags(int companyId, List<Integer> tagIds) {
        Company company = companyMapper.getCompanyById(companyId);
        if (company == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        List<String> before = tagMapper.getTagsByCompanyId(companyId).stream().map(Tag::getName).toList();
        companyMapper.clearTags(companyId);
        if (tagIds != null && !tagIds.isEmpty()) companyMapper.insertTags(companyId, tagIds);
        List<Tag> after = tagMapper.getTagsByCompanyId(companyId);
        auditService.record("company.replaceTags", "company", companyId, company.getName(),
            "Updated tags on " + company.getName(),
            auditService.singleChange("tags", before, after.stream().map(Tag::getName).toList()));
        return after;
    }

    /**
     * Retrieves the people associated with a company.
     * @param companyId
     * @return
     */
    public List<Person> getPersonsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return personMapper.getPersonsByCompanyId(companyId);
    }

    /**
     * Retrieves the deals associated with a company.
     * @param companyId
     * @return
     */
    public List<Deal> getDealsByCompanyId(int companyId) {
        if (companyMapper.getCompanyById(companyId) == null) throw new ResourceNotFoundException("Company not found with id: " + companyId);
        return dealMapper.getDealsByCompanyId(workspaceService.getCurrentWorkspaceId(), companyId);
    }
}
