package ooo.klae.connex.backend.services;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ooo.klae.connex.backend.mappers.PersonMapper;
import ooo.klae.connex.backend.mappers.TagMapper;
import ooo.klae.connex.backend.beans.Person;
import ooo.klae.connex.backend.beans.Tag;
import ooo.klae.connex.backend.exceptions.ResourceNotFoundException;
import java.util.List;

import lombok.RequiredArgsConstructor;

/**
 * Business logic for {@code Person} (contact) operations.
 * Handles mapping between {@code PersonDto} and {@code Person} bean.
 * Delegates persistence to {@code PersonMapper}.
 */

@Service
@RequiredArgsConstructor
public class PersonService {
    private final PersonMapper personMapper;
    private final TagMapper tagMapper;

    /**
     * Retrieves all {@code Person} records.
     * @return
     */
    public List<Person> getAllPersons() {
        return personMapper.getAllPersons();
    }

    public List<Person> getPersonsByCompanyId(int companyId) {
        return personMapper.getPersonsByCompanyId(companyId);
    }

    public List<Person> getPersonsByTagId(int tagId) {
        return personMapper.getPersonsByTagId(tagId);
    }

    public List<Person> getPersonsByDealId(int dealId) {
        return personMapper.getPersonsByDealId(dealId);
    }

    /**
     * Retrieves a {@code Person} by ID, throwing a {@code ResourceNotFoundException} if not found.
     * @param id
     * @return Person person
     */
    public Person getPersonById(int id) {
        Person person = personMapper.getPersonById(id);
        if (person == null) throw new ResourceNotFoundException("Person not found with id: " + id);
        return person;
    }

    /**
     * Creates a new {@code Person}. The ID is auto-generated by the database.
     * @param person
     * @return Person created person
     */
    public Person create(Person person) {
        personMapper.insert(person);
        return person;
    }

    /**
     * Updates an existing {@code Person}. Throws {@code ResourceNotFoundException} if the person does not exist.
     * @param id
     * @param person
     * @return Person updated person
     */
    public Person update(int id, Person person) {
        if (personMapper.getPersonById(id) == null) throw new ResourceNotFoundException("Person not found with id: " + id);
        person.setId(id);
        personMapper.update(person);
        return person;
    }

    /**
     * Deletes a {@code Person} by ID. Throws {@code ResourceNotFoundException} if the person does not exist.
     * @param id
     */
    public void delete(int id) {
        if (personMapper.getPersonById(id) == null) throw new ResourceNotFoundException("Person not found with id: " + id);
        personMapper.delete(id);
    }

    public List<Tag> getTagsByPersonId(int personId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        return tagMapper.getTagsByPersonId(personId);
    }

    public void addTag(int personId, int tagId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        if (tagMapper.getTagById(tagId) == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        personMapper.addTag(personId, tagId);
    }

    public void removeTag(int personId, int tagId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        personMapper.removeTag(personId, tagId);
    }

    @Transactional
    public List<Tag> replaceTags(int personId, List<Integer> tagIds) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        personMapper.clearTags(personId);
        if (tagIds != null && !tagIds.isEmpty()) personMapper.insertTags(personId, tagIds);
        return tagMapper.getTagsByPersonId(personId);
    }
}
