package ooo.klae.connex.backend.services;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ooo.klae.connex.backend.mappers.ActivityMapper;
import ooo.klae.connex.backend.mappers.DealMapper;
import ooo.klae.connex.backend.mappers.NoteMapper;
import ooo.klae.connex.backend.mappers.PersonMapper;
import ooo.klae.connex.backend.mappers.TagMapper;
import ooo.klae.connex.backend.mappers.TaskMapper;
import ooo.klae.connex.backend.beans.Activity;
import ooo.klae.connex.backend.beans.Deal;
import ooo.klae.connex.backend.beans.Note;
import ooo.klae.connex.backend.beans.Person;
import ooo.klae.connex.backend.beans.Tag;
import ooo.klae.connex.backend.beans.Task;
import ooo.klae.connex.backend.exceptions.ResourceNotFoundException;
import java.util.List;
import java.util.Set;

import lombok.RequiredArgsConstructor;

/**
 * Business logic for {@code Person} (contact) operations.
 * Handles mapping between {@code PersonDto} and {@code Person} bean.
 * Delegates persistence to {@code PersonMapper}.
 */

@Service
@RequiredArgsConstructor
public class PersonService {
    private final PersonMapper personMapper;
    private final TagMapper tagMapper;
    private final DealMapper dealMapper;
    private final ActivityMapper activityMapper;
    private final NoteMapper noteMapper;
    private final TaskMapper taskMapper;
    private final AuditService auditService;
    private final WorkspaceService workspaceService;

    private static final Set<String> AUDIT_FIELDS =
        Set.of("name", "email", "phone", "title", "imageUrl");

    /**
     * Retrieves all {@code Person} records.
     * @return
     */
    public List<Person> getAllPersons() {
        return personMapper.getAllPersons();
    }

    public List<Person> getPersonsByCompanyId(int companyId) {
        int workspaceId = workspaceService.getCurrentWorkspaceId();
        return personMapper.getPersonsByCompanyId(companyId).stream()
            .map(person -> hydrateScopedRelationships(person, workspaceId))
            .toList();
    }

    public List<Person> getPersonsByTagId(int tagId) {
        return personMapper.getPersonsByTagId(tagId);
    }

    public List<Person> getPersonsByDealId(int dealId) {
        int workspaceId = workspaceService.getCurrentWorkspaceId();
        if (!dealMapper.exists(workspaceId, dealId)) {
            throw new ResourceNotFoundException("Deal not found with id: " + dealId);
        }
        return personMapper.getPersonsByDealId(dealId);
    }

    public List<Person> getPersonsPage(String query, String sort, String dir, List<String> companies,
            List<String> titles, boolean noCompany, int limit, int offset) {
        return personMapper.getPersonsPage(query, sort, dir, companies, titles, noCompany, limit, offset);
    }

    public long countPersons(String query, List<String> companies, List<String> titles, boolean noCompany) {
        return personMapper.countPersons(query, companies, titles, noCompany);
    }

    public List<String> distinctCompanies() {
        return personMapper.distinctCompanies();
    }

    public List<String> distinctTitles() {
        return personMapper.distinctTitles();
    }

    public boolean hasPersonWithoutCompany() {
        return personMapper.hasPersonWithoutCompany();
    }

    /**
     * Retrieves a {@code Person} by ID, throwing a {@code ResourceNotFoundException} if not found.
     * @param id
     * @return Person person
     */
    public Person getPersonById(int id) {
        Person person = personMapper.getPersonById(id);
        if (person == null) throw new ResourceNotFoundException("Person not found with id: " + id);
        return hydrateScopedRelationships(person, workspaceService.getCurrentWorkspaceId());
    }

    /**
     * Creates a new {@code Person}. The ID is auto-generated by the database.
     * @param person
     * @return Person created person
     */
    public Person create(Person person) {
        personMapper.insert(person);
        auditService.record("person.create", "person", person.getId(), person.getName(),
            "Created person " + person.getName(),
            auditService.diff(null, person, AUDIT_FIELDS));
        return person;
    }

    /**
     * Updates an existing {@code Person}. Throws {@code ResourceNotFoundException} if the person does not exist.
     * @param id
     * @param person
     * @return Person updated person
     */
    public Person update(int id, Person person) {
        Person before = personMapper.getPersonById(id);
        if (before == null) throw new ResourceNotFoundException("Person not found with id: " + id);
        person.setId(id);
        personMapper.update(person);
        auditService.record("person.update", "person", id, person.getName(),
            "Updated person " + person.getName(),
            auditService.diff(before, person, AUDIT_FIELDS));
        return person;
    }

    /**
     * Deletes a {@code Person} by ID. Throws {@code ResourceNotFoundException} if the person does not exist.
     * @param id
     */
    public void delete(int id) {
        Person before = personMapper.getPersonById(id);
        if (before == null) throw new ResourceNotFoundException("Person not found with id: " + id);
        personMapper.delete(id);
        auditService.record("person.delete", "person", id, before.getName(),
            "Deleted person " + before.getName(),
            auditService.diff(before, null, AUDIT_FIELDS));
    }

    /**
     * Retrieves the tags associated with a person.
     * @param personId
     * @return
     */
    public List<Tag> getTagsByPersonId(int personId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        return tagMapper.getTagsByPersonId(personId);
    }

    /**
     * Adds a tag to a person.
     * @param personId
     * @param tagId
     */
    public void addTag(int personId, int tagId) {
        Person person = personMapper.getPersonById(personId);
        if (person == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        Tag tag = tagMapper.getTagById(workspaceService.getCurrentWorkspaceId(), tagId);
        if (tag == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        personMapper.addTag(personId, tagId);
        auditService.record("person.addTag", "person", personId, person.getName(),
            "Tagged " + person.getName() + " with " + tag.getName(),
            auditService.singleChange("tag", null, tag.getName()));
    }

    /**
     * Removes a tag from a person.
     * @param personId
     * @param tagId
     */
    public void removeTag(int personId, int tagId) {
        Person person = personMapper.getPersonById(personId);
        if (person == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        Tag tag = tagMapper.getTagById(workspaceService.getCurrentWorkspaceId(), tagId);
        personMapper.removeTag(personId, tagId);
        String tagName = tag != null ? tag.getName() : "#" + tagId;
        auditService.record("person.removeTag", "person", personId, person.getName(),
            "Removed tag " + tagName + " from " + person.getName(),
            auditService.singleChange("tag", tagName, null));
    }

    /**
     * Replaces the tags associated with a person.
     * @param personId
     * @param tagIds
     * @return
     */
    @Transactional
    public List<Tag> replaceTags(int personId, List<Integer> tagIds) {
        Person person = personMapper.getPersonById(personId);
        if (person == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        List<String> before = tagMapper.getTagsByPersonId(personId).stream().map(Tag::getName).toList();
        personMapper.clearTags(personId);
        if (tagIds != null && !tagIds.isEmpty()) personMapper.insertTags(personId, tagIds);
        List<Tag> after = tagMapper.getTagsByPersonId(personId);
        auditService.record("person.replaceTags", "person", personId, person.getName(),
            "Updated tags on " + person.getName(),
            auditService.singleChange("tags", before, after.stream().map(Tag::getName).toList()));
        return after;
    }

    /**
     * Retrieves the deals associated with a person.
     * @param personId
     * @return
     */
    public List<Deal> getDealsByPersonId(int personId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        return dealMapper.getDealsByPersonId(workspaceService.getCurrentWorkspaceId(), personId);
    }

    /**
     * Retrieves the activities associated with a person.
     * @param personId
     * @return
     */
    public List<Activity> getActivitiesByPersonId(int personId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        return activityMapper.getActivitiesByPersonId(personId);
    }

    /**
     * Retrieves the notes associated with a person.
     * @param personId
     * @return
     */
    public List<Note> getNotesByPersonId(int personId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        return noteMapper.getNotesByPersonId(personId);
    }

    /**
     * Retrieves the tasks associated with a person.
     * @param personId
     * @return
     */
    public List<Task> getTasksByPersonId(int personId) {
        if (personMapper.getPersonById(personId) == null) throw new ResourceNotFoundException("Person not found with id: " + personId);
        return taskMapper.getTasksByPersonId(workspaceService.getCurrentWorkspaceId(), personId);
    }

    private Person hydrateScopedRelationships(Person person, int workspaceId) {
        person.setDeals(dealMapper.getDealsByPersonId(workspaceId, person.getId()).toArray(Deal[]::new));
        person.setTasks(taskMapper.getTasksByPersonId(workspaceId, person.getId()).toArray(Task[]::new));
        return person;
    }
}
