package ooo.klae.connex.backend.services;

import org.springframework.stereotype.Service;

import ooo.klae.connex.backend.mappers.CompanyMapper;
import ooo.klae.connex.backend.mappers.DealMapper;
import ooo.klae.connex.backend.mappers.PersonMapper;
import ooo.klae.connex.backend.mappers.TagMapper;
import ooo.klae.connex.backend.beans.Company;
import ooo.klae.connex.backend.beans.Deal;
import ooo.klae.connex.backend.beans.Person;
import ooo.klae.connex.backend.beans.Tag;
import ooo.klae.connex.backend.exceptions.ResourceNotFoundException;

import java.util.List;
import java.util.Set;

import lombok.RequiredArgsConstructor;

/**
 * Business logic for {@code Tag} CRUD and tag-association reads.
 * Delegates persistence to {@code TagMapper}.
 */

@Service
@RequiredArgsConstructor
public class TagService {
    private final TagMapper tagMapper;
    private final DealMapper dealMapper;
    private final PersonMapper personMapper;
    private final CompanyMapper companyMapper;
    private final AuditService auditService;

    private static final Set<String> AUDIT_FIELDS =
        Set.of("name", "color");

    /**
     * Retrieves all {@code Tag} records.
     * @return
     */
    public List<Tag> getAllTags() {
        return tagMapper.getAllTags();
    }

    /**
     * Retrieves a {@code Tag} by ID, throwing a {@code ResourceNotFoundException} if not found.
     * @param id
     * @return
     */
    public Tag getTagById(int id) {
        Tag tag = tagMapper.getTagById(id);
        if (tag == null) throw new ResourceNotFoundException("Tag not found with id: " + id);
        return tag;
    }

    /**
     * Creates a new {@code Tag}. The ID is auto-generated by the database.
     * @param tag
     * @return
     */
    public Tag create(Tag tag) {
        tagMapper.insert(tag);
        auditService.record("tag.create", "tag", tag.getId(), tag.getName(),
            "Created tag " + tag.getName(),
            auditService.diff(null, tag, AUDIT_FIELDS));
        return tag;
    }

    /**
     * Updates an existing {@code Tag}. Throws {@code ResourceNotFoundException} if the tag does not exist.
     * @param id
     * @param tag
     * @return
     */
    public Tag update(int id, Tag tag) {
        Tag before = tagMapper.getTagById(id);
        if (before == null) throw new ResourceNotFoundException("Tag not found with id: " + id);
        tag.setId(id);
        tagMapper.update(tag);
        auditService.record("tag.update", "tag", id, tag.getName(),
            "Updated tag " + tag.getName(),
            auditService.diff(before, tag, AUDIT_FIELDS));
        return tag;
    }

    /**
     * Deletes a {@code Tag} by ID. Throws {@code ResourceNotFoundException} if the tag does not exist.
     * @param id
     */
    public void delete(int id) {
        Tag before = tagMapper.getTagById(id);
        if (before == null) throw new ResourceNotFoundException("Tag not found with id: " + id);
        tagMapper.delete(id);
        auditService.record("tag.delete", "tag", id, before.getName(),
            "Deleted tag " + before.getName(),
            auditService.diff(before, null, AUDIT_FIELDS));
    }

    /**
     * Retrieves the tags associated with a person.
     * @param personId
     * @return
     */
    public List<Tag> getTagsByPersonId(int personId) {
        return tagMapper.getTagsByPersonId(personId);
    }

    /**
     * Retrieves the tags associated with a company.
     * @param companyId
     * @return
     */
    public List<Tag> getTagsByCompanyId(int companyId) {
        return tagMapper.getTagsByCompanyId(companyId);
    }

    /**
     * Retrieves the tags associated with a deal.
     * @param dealId
     * @return
     */
    public List<Tag> getTagsByDealId(int dealId) {
        return tagMapper.getTagsByDealId(dealId);
    }

    /**
     * Retrieves the deals associated with a tag.
     * @param tagId
     * @return
     */
    public List<Deal> getDealsByTagId(int tagId) {
        if (tagMapper.getTagById(tagId) == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        return dealMapper.getDealsByTagId(tagId);
    }

    /**
     * Retrieves the people associated with a tag.
     * @param tagId
     * @return
     */
    public List<Person> getPersonsByTagId(int tagId) {
        if (tagMapper.getTagById(tagId) == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        return personMapper.getPersonsByTagId(tagId);
    }

    /**
     * Retrieves the companies associated with a tag.
     * @param tagId
     * @return
     */
    public List<Company> getCompaniesByTagId(int tagId) {
        if (tagMapper.getTagById(tagId) == null) throw new ResourceNotFoundException("Tag not found with id: " + tagId);
        return companyMapper.getCompaniesByTagId(tagId);
    }
}
