# spring.application.name=backend

spring:
    application:
        name: connex-backend
    datasource:
        url: jdbc:mysql://localhost:3306/connexdb
        username: connexuser
        password: connexpassword
        # driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
        init:
            mode: always
            encoding: UTF-8

mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: ooo.klae.connex.backend.beans
    configuration:
        map-underscore-to-camel-case: true
