CREATE TABLE data_subject_request (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id INT NOT NULL,
    request_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'received',
    channel VARCHAR(64) NULL,
    requester_name VARCHAR(160) NOT NULL,
    subject_name VARCHAR(160) NOT NULL,
    subject_email VARCHAR(255) NULL,
    subject_workspace_id INT NULL,
    subject_person_id INT NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    identity_verified_at DATETIME NULL,
    due_at DATETIME NULL,
    responded_at DATETIME NULL,
    closed_at DATETIME NULL,
    summary TEXT NULL,
    resolution TEXT NULL,
    created_by INT NULL,
    updated_by INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_data_subject_request_org FOREIGN KEY (org_id) REFERENCES organization(id) ON DELETE CASCADE,
    CONSTRAINT fk_data_subject_request_created_by FOREIGN KEY (created_by) REFERENCES app_user(id) ON DELETE SET NULL,
    CONSTRAINT fk_data_subject_request_updated_by FOREIGN KEY (updated_by) REFERENCES app_user(id) ON DELETE SET NULL,
    CONSTRAINT ck_data_subject_request_type CHECK (request_type IN ('disclosure', 'correction', 'cease_use', 'cease_provision')),
    CONSTRAINT ck_data_subject_request_status CHECK (status IN ('received', 'verifying', 'in_progress', 'responded', 'refused', 'closed')),
    CONSTRAINT ck_data_subject_request_subject_link CHECK ((subject_workspace_id IS NULL) = (subject_person_id IS NULL)),
    INDEX idx_data_subject_request_org_status (org_id, status, received_at),
    INDEX idx_data_subject_request_org_received (org_id, received_at)
) DEFAULT CHARSET=utf8mb4;
